services:
  # Web Service (Nexus Real-Time Node.js App)
  - type: web
    name: nexus-platform
    runtime: node
    plan: free
    buildCommand: npm install --include=dev --prefix server && npm --prefix server run build && npm install --include=dev --prefix client && npm --prefix client run build
    startCommand: node server/dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: VAPID_PUBLIC_KEY
        value: "BPmah1vTqW0sc6Q16Kr9EyX9v1fNoPUnKVkn-q24MVLK3B6BRqbM-Bz87lxvumx_W0r6hIKe3rxtOZQBo1Yqw_g"
      - key: VAPID_PRIVATE_KEY
        value: "Lu3cxCY1K0-WdsdMXenIefq4xaPC7Gr29A4SHPuOcXU"
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: VITE_FIREBASE_API_KEY
        value: "AIzaSyBGwj2ppva8ZRG1ftf7_B-0G0oGuec5paM"
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: "nexus-platform-cb84c.firebaseapp.com"
      - key: VITE_FIREBASE_PROJECT_ID
        value: "nexus-platform-cb84c"
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: "nexus-platform-cb84c.firebasestorage.app"
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: "866191964279"
      - key: VITE_FIREBASE_APP_ID
        value: "1:866191964279:web:5d6d6cd724155869b9ae72"
      - key: VITE_FIREBASE_MEASUREMENT_ID
        value: "G-WCXMQ15D9W"
      - key: FIREBASE_PROJECT_ID
        value: "nexus-platform-cb84c"
      - key: FIREBASE_STORAGE_BUCKET
        value: "nexus-platform-cb84c.firebasestorage.app"

