import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useSocket } from '../../context/SocketContext';
import { User } from '../../types';
import { Avatar } from '../common/Avatar';
import { ChatLayout } from '../chat/ChatLayout';
import { CallsView } from '../calls/CallsView';
import { DirectoryView } from '../directory/DirectoryView';
import { SubscriptionView } from '../subscription/SubscriptionView';
import { ProfileView } from '../profile/ProfileView';
import { SettingsView } from '../settings/SettingsView';
import { IncomingCallModal } from '../call/IncomingCallModal';
import { ActiveCallOverlay } from '../call/ActiveCallOverlay';
import {
  MessageSquare,
  Phone,
  Sparkles,
  User as UserIcon,
  Settings,
  Crown,
  Menu,
  X,
  Compass,
  CheckCircle2,
  ShieldCheck,
  Gem,
  Bell,
  BellRing,
} from 'lucide-react';
import axios from 'axios';
import { getNotificationPermissionStatus, requestNotificationPermission, startPushNotificationRobot } from '../../utils/notifications';
import { requestFcmToken } from '../../config/firebase';
import { UsernameSetupModal } from '../auth/UsernameSetupModal';
import { AppLockOverlay } from '../auth/AppLockOverlay';
import { GlobalAnnouncementBanner } from '../common/GlobalAnnouncementBanner';
import { AdminDashboardModal } from '../admin/AdminDashboardModal';

export type NavTab = 'chats' | 'calls' | 'directory' | 'subscription' | 'profile' | 'settings';


export const AppLayout: React.FC = () => {
  const { user } = useAuth();
  const { isConnected, callBannerMessage, latestMessage } = useSocket();

  const [currentTab, setCurrentTab] = useState<NavTab>('chats');
  const [selectedUserForChat, setSelectedUserForChat] = useState<User | null>(null);
  const [viewProfileUser, setViewProfileUser] = useState<User | null>(null);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  
  // Notification states
  const [notifPermission, setNotifPermission] = useState<'granted' | 'denied' | 'default' | 'unsupported'>('default');
  const [dismissNotifBanner, setDismissNotifBanner] = useState(false);
  const [inAppMessageToast, setInAppMessageToast] = useState<{ senderName: string; preview: string; sender?: User } | null>(null);

  // Custom Username Onboarding Modal
  const [showUsernameSetup, setShowUsernameSetup] = useState(false);

  // Royal Admin Command Center Modal
  const [isAdminModalOpen, setIsAdminModalOpen] = useState(false);

  useEffect(() => {
    if (user) {
      const alreadySet = localStorage.getItem(`nexus_custom_username_set_${user.id}`);
      const looksAutoGenerated = /_[a-z0-9]{4}$/i.test(user.username) || user.username.startsWith('user_');
      if (!alreadySet && looksAutoGenerated) {
        setShowUsernameSetup(true);
      }
    }
  }, [user?.id, user?.username]);

  useEffect(() => {
    // 🤖 Royal Push Notification Robot: Auto-registers push on app launch
    const cleanupRobot = startPushNotificationRobot({
      onStatusChange: (status) => setNotifPermission(status),
    });
    return () => cleanupRobot();
  }, [user?.id]);


  const handleEnableNotifications = async () => {
    const granted = await requestNotificationPermission();
    if (granted) {
      setNotifPermission('granted');
      setDismissNotifBanner(true);
    } else {
      setNotifPermission(getNotificationPermissionStatus());
    }
  };

  // Listen to incoming messages for in-app floating banner
  useEffect(() => {
    if (!latestMessage || latestMessage.sender_id === user?.id) return;
    if (currentTab === 'chats' && selectedUserForChat?.id === latestMessage.sender_id) return;

    const senderName = latestMessage.sender?.full_name || latestMessage.sender?.username || 'Nexus Contact';
    const preview = latestMessage.type === 'audio'
      ? '🎤 Voice Message'
      : latestMessage.type === 'image'
      ? '📷 Photo'
      : latestMessage.content || 'Sent an attachment';

    setInAppMessageToast({
      senderName,
      preview,
      sender: latestMessage.sender,
    });

    const timer = setTimeout(() => {
      setInAppMessageToast(null);
    }, 5000);
    return () => clearTimeout(timer);
  }, [latestMessage, currentTab, selectedUserForChat?.id, user?.id]);


  const handleStartChatWithUser = (targetUser: User) => {
    setSelectedUserForChat(targetUser);
    setCurrentTab('chats');
  };

  const handleViewProfile = (targetUser: User) => {
    setViewProfileUser(targetUser);
    setCurrentTab('profile');
  };

  const navItems: Array<{ id: NavTab; label: string; icon: any; badge?: string }> = [
    { id: 'chats', label: 'Messages', icon: MessageSquare },
    { id: 'calls', label: 'Calls', icon: Phone },
    { id: 'directory', label: 'Community', icon: Compass },
    { id: 'profile', label: 'My Passport', icon: UserIcon },
    { id: 'settings', label: 'Settings', icon: Settings },
  ];

  return (
    <div className="h-[100dvh] bg-dark-950 text-dark-100 flex flex-col selection:bg-gold-500 selection:text-dark-950 overflow-hidden font-['Plus_Jakarta_Sans',sans-serif]">
      
      {/* 🔐 Royal Vault PIN Lock (protects all views when enabled) */}
      <AppLockOverlay />

      {/* Global Call Modals (always listening) */}
      <IncomingCallModal />
      <ActiveCallOverlay />

      {/* Global Toast / Banner Notification */}
      {callBannerMessage && (
        <div className="fixed top-4 left-1/2 -translate-x-1/2 z-50 px-5 py-2.5 rounded-2xl bg-dark-900/95 border border-gold-500/40 text-amber-200 text-xs font-semibold shadow-2xl shadow-gold-500/20 backdrop-blur-xl flex items-center gap-2 animate-in fade-in">
          <Crown className="w-4 h-4 text-gold-400 animate-pulse" />
          <span>{callBannerMessage}</span>
        </div>
      )}

      {/* 💬 Floating In-App Chat Toast */}
      {inAppMessageToast && (
        <div
          onClick={() => {
            if (inAppMessageToast.sender) {
              handleStartChatWithUser(inAppMessageToast.sender);
            } else {
              setCurrentTab('chats');
            }
            setInAppMessageToast(null);
          }}
          className="fixed top-16 right-3 sm:right-6 z-50 max-w-sm w-[calc(100vw-1.5rem)] bg-dark-900/95 border border-gold-500/40 rounded-2xl p-3 sm:p-3.5 shadow-2xl shadow-black/90 backdrop-blur-2xl flex items-center gap-3 cursor-pointer hover:border-gold-400 transition-all animate-in slide-in-from-top-3"
        >
          <div className="w-10 h-10 rounded-full bg-gold-500/10 border border-gold-500/30 flex items-center justify-center shrink-0 text-gold-400 overflow-hidden">
            {inAppMessageToast.sender?.avatar_url ? (
              <img src={inAppMessageToast.sender.avatar_url} alt="" className="w-full h-full object-cover" />
            ) : (
              <MessageSquare className="w-5 h-5 text-gold-400" />
            )}
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center justify-between gap-1">
              <p className="text-xs font-bold text-white truncate">{inAppMessageToast.senderName}</p>
              <span className="text-[10px] text-gold-400 font-semibold shrink-0">Just now</span>
            </div>
            <p className="text-xs text-dark-300 truncate mt-0.5">{inAppMessageToast.preview}</p>
          </div>
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              setInAppMessageToast(null);
            }}
            className="p-1 text-dark-400 hover:text-white shrink-0"
          >
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      {/* 👑 Royal Top Navbar */}
      <header className="h-14 sm:h-16 border-b border-gold-500/15 bg-dark-900/90 backdrop-blur-2xl sticky top-0 z-40 px-3.5 sm:px-6 flex items-center justify-between shrink-0 shadow-lg shadow-black/40">
        
        {/* Royal Brand Logo & Connection Status */}
        <div className="flex items-center gap-2.5 sm:gap-3.5">
          <div
            onClick={() => { setCurrentTab('chats'); setSelectedUserForChat(null); }}
            className="flex items-center gap-2 sm:gap-2.5 cursor-pointer group"
          >
            <div className="w-8 h-8 sm:w-9 sm:h-9 rounded-xl bg-gradient-to-tr from-amber-600 via-yellow-500 to-amber-400 flex items-center justify-center text-dark-950 shadow-lg shadow-gold-500/30 group-hover:scale-105 group-hover:rotate-3 transition-all shrink-0">
              <Crown className="w-4 h-4 sm:w-5 sm:h-5 fill-dark-950" />
            </div>
            <div>
              <span className="text-sm sm:text-base font-extrabold tracking-tight flex items-center gap-1.5 leading-none">
                <span className="gold-gradient-text tracking-wide font-black">NEXUS</span>
                <span className="text-[9px] font-black px-2 py-0.5 rounded-full bg-gradient-to-r from-amber-500/25 via-yellow-400/20 to-amber-600/25 text-amber-300 border border-amber-400/40 shadow-xs tracking-widest uppercase">
                  ROYAL
                </span>
              </span>
            </div>
          </div>

          <div className="flex items-center gap-1.5 text-[10px] sm:text-[11px] px-2.5 py-0.5 rounded-full bg-dark-850/90 border border-gold-500/20 text-dark-300 shadow-inner">
            <span className={`w-2 h-2 rounded-full ${isConnected ? 'bg-emerald-400 shadow-[0_0_8px_#10b981]' : 'bg-rose-400 animate-pulse'}`} />
            <span className="hidden xs:inline font-medium text-dark-300">{isConnected ? 'Royal Gateway' : 'Connecting...'}</span>
          </div>

          {(user?.role === 'admin' || user?.email?.toLowerCase().includes('karthikarthiswaran50') || user?.username?.toLowerCase() === 'karthikarthiswaran50') && (
            <button
              type="button"
              onClick={() => setIsAdminModalOpen(true)}
              className="flex items-center gap-1.5 text-[10px] sm:text-[11px] px-2.5 py-1 rounded-full bg-gradient-to-r from-amber-500/20 via-yellow-500/15 to-amber-600/20 border border-amber-400/40 text-amber-300 font-extrabold shadow-sm hover:scale-105 transition-all cursor-pointer"
            >
              <Crown className="w-3 h-3 text-amber-400" />
              <span>👑 Owner Panel</span>
            </button>
          )}
        </div>

        {/* Desktop Navigation Tabs (Royal Glass) */}
        <nav className="hidden md:flex items-center gap-1.5 bg-dark-950/80 p-1.5 rounded-2xl border border-gold-500/15 shadow-inner">
          {navItems.map((item) => {
            const Icon = item.icon;
            const isActive = currentTab === item.id;

            return (
              <button
                key={item.id}
                type="button"
                onClick={() => {
                  setCurrentTab(item.id);
                  if (item.id === 'profile') setViewProfileUser(null);
                }}
                className={`relative px-3.5 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all ${
                  isActive
                    ? 'bg-gradient-to-r from-amber-500 via-yellow-500 to-amber-600 text-dark-950 shadow-lg shadow-gold-500/25 scale-[1.02]'
                    : 'text-dark-300 hover:text-amber-200 hover:bg-dark-800/80'
                }`}
              >
                <Icon className={`w-4 h-4 ${isActive ? 'fill-dark-950 text-dark-950' : 'text-gold-400'}`} />
                <span>{item.label}</span>
                {item.badge && (
                  <span
                    className={`text-[9px] px-1.5 py-0.2 rounded-full font-extrabold uppercase ${
                      isActive
                        ? 'bg-dark-950/30 text-dark-950'
                        : item.badge === 'VIP'
                        ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40 shadow-xs'
                        : item.badge === 'PRO'
                        ? 'bg-brand-500/20 text-brand-300 border border-brand-500/40'
                        : 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                    }`}
                  >
                    {item.badge}
                  </span>
                )}
              </button>
            );
          })}
        </nav>

        {/* User Status Card & Actions */}
        <div className="flex items-center gap-2 sm:gap-2.5">
          

          <button
            type="button"
            onClick={() => { setCurrentTab('profile'); setViewProfileUser(null); }}
            className="flex items-center gap-2 p-1 sm:p-1.5 sm:pr-3 rounded-2xl bg-dark-850/80 hover:bg-dark-800 border border-gold-500/20 transition-all text-left group"
          >
            <Avatar
              src={user?.avatar_url}
              name={user?.full_name || ''}
              size="sm"
              isOnline={isConnected}
              showOnlineStatus
              planId={user?.plan_id}
            />
            <div className="hidden lg:block">
              <p className="text-xs font-extrabold text-white leading-tight truncate max-w-[120px] group-hover:text-amber-200 transition-colors">{user?.full_name}</p>
              <p className="text-[10px] text-gold-400/80 uppercase font-bold tracking-wider">👑 Royal Member</p>
            </div>
          </button>

          {/* Mobile Menu Button */}
          <button
            type="button"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="md:hidden p-1.5 rounded-xl bg-dark-850 text-gold-400 hover:text-white border border-gold-500/20"
          >
            {mobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
          </button>
        </div>
      </header>

      {/* 🤖 Royal Auto-Push Notification Robot Activation Ribbon */}
      {notifPermission === 'default' && !dismissNotifBanner && (
        <div className="bg-gradient-to-r from-amber-600/25 via-yellow-500/20 to-amber-600/25 border-b border-gold-500/35 px-3.5 sm:px-6 py-2.5 flex items-center justify-between gap-3 text-xs text-amber-200 z-30 shrink-0 shadow-lg">
          <div className="flex items-center gap-2.5 min-w-0">
            <div className="w-7 h-7 sm:w-8 sm:h-8 rounded-xl bg-gold-500/20 border border-gold-400/40 flex items-center justify-center shrink-0 text-amber-300 shadow-sm">
              <BellRing className="w-4 h-4 text-amber-300 animate-bounce" />
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-1.5">
                <span className="font-black text-white text-xs">🤖 Auto-Push Robot</span>
                <span className="text-[9px] px-1.5 py-0.2 rounded bg-amber-500/25 text-amber-300 border border-amber-400/35 uppercase font-black tracking-wider">Live</span>
              </div>
              <p className="truncate text-[11px] text-dark-300 mt-0.5">
                Turn on alerts so your phone rings for incoming calls and messages even when the app is closed.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <button
              type="button"
              onClick={handleEnableNotifications}
              className="px-3 sm:px-4 py-1.5 bg-gradient-to-r from-amber-500 via-yellow-400 to-amber-600 hover:from-amber-400 hover:to-yellow-300 text-dark-950 font-black rounded-xl text-xs shadow-md shadow-gold-500/25 transition-all active:scale-95 flex items-center gap-1.5 cursor-pointer"
            >
              <Bell className="w-3.5 h-3.5 stroke-[2.5]" />
              <span>Turn On Alerts</span>
            </button>
            <button
              type="button"
              onClick={() => setDismissNotifBanner(true)}
              className="p-1.5 text-dark-400 hover:text-white rounded-lg transition-colors cursor-pointer"
              title="Dismiss"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* ⚠️ Warning if user previously blocked notifications in browser */}
      {notifPermission === 'denied' && !dismissNotifBanner && (
        <div className="bg-rose-950/40 border-b border-rose-500/30 px-3.5 sm:px-6 py-2 flex items-center justify-between gap-2.5 text-xs text-rose-200 z-30 shrink-0">
          <div className="flex items-center gap-2 min-w-0">
            <span className="text-sm">🔒</span>
            <span className="truncate text-[11px] sm:text-xs">
              Notifications are blocked in your browser. Tap the <strong>lock / tune icon</strong> in your browser address bar to Allow.
            </span>
          </div>
          <button
            type="button"
            onClick={() => setDismissNotifBanner(true)}
            className="p-1 text-rose-300 hover:text-white rounded-md transition-colors shrink-0"
          >
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      {/* Mobile Drawer Menu (Royal) */}
      {mobileMenuOpen && (
        <div className="md:hidden bg-dark-900 border-b border-gold-500/20 p-4 space-y-2 animate-in slide-in-from-top duration-200 z-30 shrink-0 shadow-2xl">
          {navItems.map((item) => {
            const Icon = item.icon;
            const isActive = currentTab === item.id;
            return (
              <button
                key={item.id}
                type="button"
                onClick={() => {
                  setCurrentTab(item.id);
                  if (item.id === 'profile') setViewProfileUser(null);
                  setMobileMenuOpen(false);
                }}
                className={`w-full px-4 py-2.5 rounded-xl text-xs font-bold flex items-center justify-between transition-all ${
                  isActive ? 'bg-gradient-to-r from-amber-500 to-yellow-500 text-dark-950 shadow-md' : 'text-dark-300 hover:bg-dark-800'
                }`}
              >
                <div className="flex items-center gap-3">
                  <Icon className={`w-4 h-4 ${isActive ? 'text-dark-950' : 'text-gold-400'}`} />
                  <span>{item.label}</span>
                </div>
                {item.badge && (
                  <span className="text-[10px] px-2 py-0.5 rounded-full font-bold bg-dark-800 text-gold-300 border border-gold-500/20">
                    {item.badge}
                  </span>
                )}
              </button>
            );
          })}
        </div>
      )}

      {/* Main App Content Body */}
      <main className="flex-1 flex flex-col overflow-hidden min-h-0 relative">
        
        {/* Subtle Ambient Gold Light Orb */}
        <div className="pointer-events-none absolute -top-40 left-1/2 -translate-x-1/2 w-96 h-96 bg-gold-500/5 rounded-full blur-3xl" />

        {currentTab === 'chats' && (
          <div className="flex-1 flex overflow-hidden">
            <ChatLayout
              initialSelectedUser={selectedUserForChat}
              onNavigateToDirectory={() => setCurrentTab('directory')}
              onNavigateToSubscription={() => setCurrentTab('subscription')}
              onViewProfile={handleViewProfile}
            />
          </div>
        )}

        {currentTab === 'calls' && (
          <div className="flex-1 overflow-y-auto p-3.5 sm:p-6 pb-20 md:pb-6">
            <CallsView
              onStartChat={handleStartChatWithUser}
              onViewProfile={handleViewProfile}
            />
          </div>
        )}

        {currentTab === 'directory' && (
          <div className="flex-1 overflow-y-auto p-3.5 sm:p-6 pb-20 md:pb-6">
            <DirectoryView
              onStartChat={handleStartChatWithUser}
              onViewProfile={handleViewProfile}
            />
          </div>
        )}

        {currentTab === 'subscription' && (
          <div className="flex-1 overflow-y-auto p-3.5 sm:p-6 pb-20 md:pb-6">
            <SubscriptionView />
          </div>
        )}

        {currentTab === 'profile' && (
          <div className="flex-1 overflow-y-auto p-3.5 sm:p-6 pb-20 md:pb-6">
            <ProfileView
              viewUser={viewProfileUser}
              onNavigateToSubscription={() => setCurrentTab('subscription')}
            />
          </div>
        )}

        {currentTab === 'settings' && (
          <div className="flex-1 overflow-y-auto p-3.5 sm:p-6 pb-20 md:pb-6">
            <SettingsView />
          </div>
        )}
      </main>

      {/* 👑 Royal Mobile Bottom Navigation Bar (WhatsApp Style, 1-thumb touch) */}
      <nav className="md:hidden h-14 sm:h-16 bg-dark-900/95 backdrop-blur-2xl border-t border-gold-500/20 z-40 flex items-center justify-around px-2 shrink-0 pb-[env(safe-area-inset-bottom)] shadow-2xl">
        <button
          type="button"
          onClick={() => { setCurrentTab('chats'); setSelectedUserForChat(null); }}
          className={`flex flex-col items-center gap-0.5 py-1 px-3 rounded-xl transition-all ${
            currentTab === 'chats' ? 'text-amber-300 font-extrabold scale-105' : 'text-dark-400'
          }`}
        >
          <MessageSquare className="w-5 h-5" />
          <span className="text-[10px]">Chat</span>
        </button>

        <button
          type="button"
          onClick={() => setCurrentTab('calls')}
          className={`flex flex-col items-center gap-0.5 py-1 px-3 rounded-xl transition-all ${
            currentTab === 'calls' ? 'text-amber-300 font-extrabold scale-105' : 'text-dark-400'
          }`}
        >
          <Phone className="w-5 h-5" />
          <span className="text-[10px]">Calls</span>
        </button>

        <button
          type="button"
          onClick={() => setCurrentTab('directory')}
          className={`flex flex-col items-center gap-0.5 py-1 px-3 rounded-xl transition-all ${
            currentTab === 'directory' ? 'text-amber-300 font-extrabold scale-105' : 'text-dark-400'
          }`}
        >
          <Compass className="w-5 h-5" />
          <span className="text-[10px]">Users</span>
        </button>

        <button
          type="button"
          onClick={() => { setCurrentTab('profile'); setViewProfileUser(null); }}
          className={`flex flex-col items-center gap-0.5 py-1 px-3 rounded-xl transition-all ${
            currentTab === 'profile' ? 'text-amber-300 font-extrabold scale-105' : 'text-dark-400'
          }`}
        >
          <UserIcon className="w-5 h-5" />
          <span className="text-[10px]">Passport</span>
        </button>
      </nav>


      {/* Custom Unique Username / Royal ID Onboarding Modal */}
      <UsernameSetupModal
        isOpen={showUsernameSetup}
        onClose={() => setShowUsernameSetup(false)}
      />

      {/* Global Royal Announcements Banner */}
      <GlobalAnnouncementBanner />

      {/* Royal Admin Command Center Modal */}
      <AdminDashboardModal
        isOpen={isAdminModalOpen}
        onClose={() => setIsAdminModalOpen(false)}
      />

    </div>
  );
};

